<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::table('status_reasons', function (Blueprint $table) {
            $table->string('series')->nullable()->after('code');
            $table->text('assignment_condition')->nullable()->after('label');
            $table->text('notes')->nullable()->after('assignment_condition');
            $table->boolean('suspend_submissions')->default(false)->after('notes');
            $table->boolean('client_may_replace')->default(false)->after('suspend_submissions');
            $table->boolean('suspend_interest')->default(false)->after('client_may_replace');
            $table->boolean('requires_management_approval')->default(false)->after('suspend_interest');
            $table->boolean('triggers_insurance_claim')->default(false)->after('requires_management_approval');
            $table->boolean('blocks_new_loan')->default(false)->after('triggers_insurance_claim');
            $table->boolean('allows_manager_override')->default(false)->after('blocks_new_loan');
            $table->boolean('requires_mode_of_exit')->default(false)->after('allows_manager_override');
            $table->boolean('requires_affordability_reason')->default(false)->after('requires_mode_of_exit');
            $table->json('input_options')->nullable()->after('requires_affordability_reason');
        });

        Schema::create('status_reason_events', function (Blueprint $table) {
            $table->id();
            $table->foreignId('loan_record_id')->nullable()->constrained('loans')->nullOnDelete();
            $table->string('loan_id');
            $table->string('client_id')->nullable();
            $table->string('nrc')->nullable();
            $table->foreignId('previous_status_reason_id')->nullable()->constrained('status_reasons')->nullOnDelete();
            $table->foreignId('status_reason_id')->nullable()->constrained('status_reasons')->nullOnDelete();
            $table->string('action');
            $table->date('effective_date');
            $table->string('mode_of_exit')->nullable();
            $table->string('affordability_reason')->nullable();
            $table->boolean('management_approval_confirmed')->default(false);
            $table->text('notes')->nullable();
            $table->text('removal_reason')->nullable();
            $table->foreignId('performed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('performed_by_name')->nullable();
            $table->json('metadata')->nullable();
            $table->timestamps();

            $table->index(['loan_id', 'created_at']);
            $table->index(['action', 'effective_date']);
        });

        $now = now();

        DB::table('status_reasons')->upsert([
            [
                'code' => 'A001',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Below Affordability',
                'assignment_condition' => 'Assign when receipting identifies a shortfall due to reduced affordability.',
                'notes' => 'Still submitted at reduced affordable amount.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => true,
                'input_options' => json_encode([
                    'affordability_reason' => [
                        'New Third Party - Loan Month',
                        'New Third Party - Submission Month',
                        'Dropped Housing Allowance',
                        'Rural Hardship Allowance Reduction',
                        'Teachers Allowance Reduction',
                        'Other',
                    ],
                ]),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A002',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Payroll Error',
                'assignment_condition' => 'Assign when payroll failed despite correct submission and no affordability issue.',
                'notes' => 'Keep submitting while payroll cause is unresolved.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A003',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Administrative Error',
                'assignment_condition' => 'Assign when an internal submission error caused the missed deduction.',
                'notes' => 'Keep submitting and correct the error next month.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A004',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Salary Locked / Disciplinary',
                'assignment_condition' => 'Assign when GRZ disciplinary proceedings lock salary access.',
                'notes' => 'Blocks new loan issuance until the code is removed.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A005',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Leave Without Pay',
                'assignment_condition' => 'Assign when approved leave without pay is confirmed.',
                'notes' => 'Suspend payroll submissions while leave without pay is active.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A006',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Reinstated at Payroll',
                'assignment_condition' => 'Assign when a previously off-payroll client is reinstated and deductions can resume.',
                'notes' => 'Typically replaces A007.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A007',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Off Payroll',
                'assignment_condition' => 'Assign when a client exits payroll for any reason.',
                'notes' => 'Blocks new loans and allows replacement loans.',
                'suspend_submissions' => true,
                'client_may_replace' => true,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => true,
                'requires_affordability_reason' => false,
                'input_options' => json_encode([
                    'mode_of_exit' => [
                        'Dismissed',
                        'Resigned',
                        'Seconded',
                        'Retired',
                        'Contract Not Renewed',
                        'Misconduct',
                    ],
                ]),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A008',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Off Payroll - Interest Suspended',
                'assignment_condition' => 'Assign when an off-payroll client is unlikely to recover in full and management approved interest suspension.',
                'notes' => 'Management approval is required before activation.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => true,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A009',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Failed Migration at Payroll',
                'assignment_condition' => 'Assign when a migration loan payroll deduction component fails.',
                'notes' => null,
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A010',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Migration (Split Collection)',
                'assignment_condition' => 'Assign when instalments are split between payroll and DDACC from first submission month.',
                'notes' => 'Payroll portion remains active.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A011',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Failed Migration at Bank',
                'assignment_condition' => 'Assign when the DDACC or bank component of a migration loan fails.',
                'notes' => 'Payroll component continues.',
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A012',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Third Party Still Deducting',
                'assignment_condition' => 'Assign to refinancing loans where the first instalment cannot be recovered because a prior lender deduction is still active.',
                'notes' => null,
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A013',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Legal',
                'assignment_condition' => 'Assign when legal recovery is underway and payroll deduction is not possible.',
                'notes' => 'Blocks new loan issuance.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A014',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Upward Adjusted at Payroll',
                'assignment_condition' => 'Assign when payroll submission is raised above the contractual instalment to cure arrears faster.',
                'notes' => null,
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'A015',
                'series' => 'A-Series',
                'group' => 'Arrears & Operational',
                'label' => 'Reverted to Full Instalment',
                'assignment_condition' => 'Assign when a previously adjusted or reduced loan is back at its contractual instalment.',
                'notes' => null,
                'suspend_submissions' => false,
                'client_may_replace' => false,
                'suspend_interest' => false,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => false,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'D001',
                'series' => 'D-Series',
                'group' => 'Doubtful Loans',
                'label' => 'Doubtful - Contract Not Renewed',
                'assignment_condition' => 'Assign when an off-payroll contract-not-renewed client is 120+ DPD and unpaid for 6+ months.',
                'notes' => 'Blocks new loan issuance and triggers insurance review.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => true,
                'triggers_insurance_claim' => true,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'D002',
                'series' => 'D-Series',
                'group' => 'Doubtful Loans',
                'label' => 'Doubtful - Dismissed',
                'assignment_condition' => 'Assign when a dismissed client is 120+ DPD and unpaid for 6+ months.',
                'notes' => 'Blocks new loan issuance and requires management approval for suspended interest.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => true,
                'triggers_insurance_claim' => true,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'D003',
                'series' => 'D-Series',
                'group' => 'Doubtful Loans',
                'label' => 'Doubtful - Resigned',
                'assignment_condition' => 'Assign when a resigned client is 120+ DPD and unpaid for 6+ months.',
                'notes' => 'Blocks new loan issuance and requires management approval for suspended interest.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => true,
                'triggers_insurance_claim' => true,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'D004',
                'series' => 'D-Series',
                'group' => 'Doubtful Loans',
                'label' => 'Doubtful - Secondment',
                'assignment_condition' => 'Assign when a seconded client is 120+ DPD and unpaid for 6+ months.',
                'notes' => 'Blocks new loan issuance and requires management approval for suspended interest.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => true,
                'triggers_insurance_claim' => true,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'I001',
                'series' => 'I-Series',
                'group' => 'Insurance & Medical',
                'label' => 'Deceased Client',
                'assignment_condition' => 'Assign upon confirmed notification that the client is deceased.',
                'notes' => 'Triggers insurance claim process and blocks new loans.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => true,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'I002',
                'series' => 'I-Series',
                'group' => 'Insurance & Medical',
                'label' => 'Medical Discharge',
                'assignment_condition' => 'Assign upon confirmed notification that the client has been medically discharged.',
                'notes' => 'Triggers insurance claim process and blocks new loans.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => true,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'I003',
                'series' => 'I-Series',
                'group' => 'Insurance & Medical',
                'label' => 'Repudiated Claim',
                'assignment_condition' => 'Assign when an insurance claim was processed and rejected.',
                'notes' => 'Blocks new loan issuance.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => true,
                'allows_manager_override' => false,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'W001',
                'series' => 'W-Series',
                'group' => 'Write-Off',
                'label' => '2026 Write-Off',
                'assignment_condition' => 'Assign when a loan is approved for write-off in the 2026 financial year.',
                'notes' => 'New loan eligibility requires manager override.',
                'suspend_submissions' => true,
                'client_may_replace' => false,
                'suspend_interest' => true,
                'requires_management_approval' => false,
                'triggers_insurance_claim' => false,
                'blocks_new_loan' => true,
                'allows_manager_override' => true,
                'requires_mode_of_exit' => false,
                'requires_affordability_reason' => false,
                'input_options' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['code'], [
            'series',
            'group',
            'label',
            'assignment_condition',
            'notes',
            'suspend_submissions',
            'client_may_replace',
            'suspend_interest',
            'requires_management_approval',
            'triggers_insurance_claim',
            'blocks_new_loan',
            'allows_manager_override',
            'requires_mode_of_exit',
            'requires_affordability_reason',
            'input_options',
            'is_active',
            'updated_at',
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('status_reason_events');

        Schema::table('status_reasons', function (Blueprint $table) {
            $table->dropColumn([
                'series',
                'assignment_condition',
                'notes',
                'suspend_submissions',
                'client_may_replace',
                'suspend_interest',
                'requires_management_approval',
                'triggers_insurance_claim',
                'blocks_new_loan',
                'allows_manager_override',
                'requires_mode_of_exit',
                'requires_affordability_reason',
                'input_options',
            ]);
        });
    }
};
